POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Joe2",
    "lastName":"Messy2",
    "email": "joe@messy2.com",
    "password": "Password@124"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json

{
"users" : [
{
    "firstName": "Mark",
    "lastName":"Doe",
     "email": "joe@messy21.com",
    "password": "Password@124"
},
{
    "firstName": "Tom",
    "lastName":"Doe",
    "email": "tom@doe2.com",
    "password": "Password@124"
}
]
}
