POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI2LCJlbWFpbCI6ImpvZUBtZXNzeTIuY29tIiwiaWF0IjoxNzQ0MDA1OTgxLCJleHAiOjE3NDQwMDk1ODEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.ZOzwftnGLDMSbAfh2fG58_7_tEmdIbVtLKS0qZIHJSQ

{
    "firstName": "Joe2",
    "lastName":"Messy2",
    "email": "joe@messy2.com",
    "password": "Password@124"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI2LCJlbWFpbCI6ImpvZUBtZXNzeTIuY29tIiwiaWF0IjoxNzQzNjg0MjQ4LCJleHAiOjE3NDM2ODc4NDgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Nl65545YqvYkwntXJOPp1gKqPOmuZMqa0UkOIw_eUIM

{
"users" : [
{
    "firstName": "Mark",
    "lastName":"Doe",
     "email": "joe@messy21.com",
    "password": "Password@124"
},
{
    "firstName": "Tom",
    "lastName":"Doe",
    "email": "tom@doe2.com",
    "password": "Password@124"
}
]
}
